### ISSUE TITLE
Issue with /docs/user-guide/jobs/

### ISSUE THREAD

**Issue by razghe** [kubernetes/kubernetes.github.io#1220]
Issue with /docs/user-guide/jobs/

When following the documentation, on section jobs, "Running an example Job". The examples in the documentation do not match with the result on the local instance of our kubernetes cluster

Documentation example, creating the job.yaml file and creating the job

The result should be:

```
$ kubectl describe jobs/pi
Name:		pi
Namespace:	default
Image(s):	perl
Selector:       controller-uid=b1db589a-2c8d-11e6-b324-0209dc45a495
Parallelism:	1
Completions:	1
Start Time:     Tue, 07 Jun 2016 10:56:16 +0200
Labels:         controller-uid=b1db589a-2c8d-11e6-b324-0209dc45a495,job-name=pi
Pods Statuses:	0 Running / 1 Succeeded / 0 Failed
No volumes.
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  1m		1m		1	{job-controller }			Normal		SuccessfulCreate	Created pod: pi-dtn4q
```

On my local machine the result is the following:

```
host-44-11-1-22:~ # kubectl describe jobs/pi
Name:           pi
Namespace:      default
Image(s):       perl
Selector:       controller-uid=2d24e2be-79c4-11e6-aef4-fa163e39bb70
Parallelism:    1
Completions:    1
Labels:         controller-uid=2d24e2be-79c4-11e6-aef4-fa163e39bb70
                job-name=pi
Pods Statuses:  0 Running / 0 Succeeded / 0 Failed
No volumes.
No events.
```
```
host-44-11-1-22:~ # cat job1.yaml 
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    metadata:
      name: pi
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
```

Why do I have no pods created and 0 Succeeded Pods status?

Thanks,
razvan
