### ISSUE TITLE
Issue with /docs/admin/authentication/#service-account-tokens

### ISSUE THREAD

**Issue by sirhopcount** [kubernetes/kubernetes.github.io#2333]
**This is a...** 
- [ ] Feature Request
- [X] Bug Report

**Problem:**
Incorrect example at "Service Account Tokens". The documentation states:

> Accounts may be explicitly associated with pods using the serviceAccountName field of a PodSpec.

But in the example the serviceAccountName field has been set in the container field.

**Proposed Solution:**

Replace:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
    # ...
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        serviceAccountName: bob-the-bot
```
With:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
    # ...
    spec:
      serviceAccountName: bob-the-bot
      containers:
      - name: nginx
        image: nginx:1.7.9
```

**Page to Update:**
http://kubernetes.io/docs/admin/authentication/#service-account-tokens
