### ISSUE TITLE
Issue with /docs/tasks/run-application/rolling-update-replication-controller/

### ISSUE THREAD

**Issue by chinakevinguo** [kubernetes/kubernetes.github.io#2857]
Hi 
    My k8s version is 1.5.2
    rolling update from rc file, get error 
```
error: ./webapp-rc-v2.yaml must specify a matching key with non-equal value in Selector for webapp
````

Here is webapp-rc.yaml
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
      - name: webapp
        image: tomcat
        ports:
        - containerPort: 80
```

Here is webapp-rc-v2.yaml
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp-v2
spec:
  replicas: 2
  selector:
    name: webapp
    version: v2
  template:
    metadata:
      labels:
        name: webapp
        version: v2
    spec:
      containers:
      - name: webapp
        image: nginx
        ports:
        - containerPort: 80
```

commands

```
kubectl rolling-update webapp -f ./webapp-rc-v2.yaml
```
