### ISSUE TITLE
Issue with /docs/concepts/ecosystem/thirdpartyresource/

### ISSUE THREAD

**Issue by jeremyjjbrown** [kubernetes/kubernetes.github.io#3254]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
It looks like my-crontab.yaml from the tutorial is not valid

```yaml
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
cronSpec: "* * * * /5"
image: my-awesome-cron-image
```

 kubectl create -f 3rdparty/my-crontab.yaml 
yaml: line 5: did not find expected key

**Proposed Solution:**

Maybe this is correct
```yaml
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
    name: my-new-cron-object
spec:
    cronSpec: "* * * * /5"
    image: my-awesome-cron-image
```

**Page to Update:**
https://kubernetes.io/docs/concepts/ecosystem/thirdpartyresource/

Kubernetes Version:
minikube version: v0.17.1
