### ISSUE TITLE
Example for podAntiAffinity with preferredDuringSchedulingIgnoredDuringExecution

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes.github.io#3629]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

We are using `requiredDuringSchedulingIgnoredDuringExecution` for the example of `podAntiAffinity` and `podAffinity`, it is better to update `podAntiAffinity` to use `preferredDuringSchedulingIgnoredDuringExecution` so that we can cover both kind of affinity in one example.
 
```
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - S1
        topologyKey: failure-domain.beta.kubernetes.io/zone
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - S2
        topologyKey: kubernetes.io/hostname
  containers:
  - name: with-pod-affinity
    image: gcr.io/google_containers/pause:2.0
```

**Proposed Solution:**
```
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - S1
        topologyKey: failure-domain.beta.kubernetes.io/zone
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: security
              operator: In
              values:
              - S2
          topologyKey: kubernetes.io/hostname
  containers:
  - name: with-pod-affinity
    image: gcr.io/google_containers/pause:2.0
```

**Page to Update:**
http://kubernetes.io/...
