### ISSUE TITLE
clusterrole 'cluster-status' is documented but not implemented

### ISSUE THREAD

**Issue by erikmack** [kubernetes/kubernetes.github.io#3813]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Docs refer to a clusterrole called 'cluster-status' which does not exist in kubernetes.  The first mention of cluster-status was in commit a6c76bb8141b033b1bc1d46e94169abd8a7cca91.  The clusterrole is nowhere in kubernetes source code, including the list of bootstrap clusterroles:  https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L90

**Proposed Solution:**
Remove mention of cluster-status clusterrole

**Page to Update:**
http://kubernetes.io/docs/admin/authorization/rbac/

Kubernetes Version: 1.6.2

Additional Information:  Is there an equivalent?  The clusterrole would be useful, since my non-admin users can't e.g. 'kubectl get nodes'

**Comment by mryan43** [comment]
Same problem, I ended up giving the "view" clusterrole to those users with a clusterrolebinding because that was fine in my case.

If you just want them to be able to see nodes, you can try : 
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: view-nodes
rules:
- resources: ["nodes"]
  verbs: ["get", "watch", "list"]

```
