### ISSUE TITLE
secrets syntax error in volume spec in k8s.io/docs/tasks/inject-data-application/podpreset/

### ISSUE THREAD

**Issue by discordianfish** [kubernetes/kubernetes.github.io#4377]
It says (twice):
```
  volumes:
    - name: cache-volume
      emptyDir: {}
    - name: secret-volume
      secretName: config-details
```

but should say:
```
  volumes:
    - name: cache-volume
      emptyDir: {}
    - name: secret-volume
      secret:
        secretName: config-details
```
