### ISSUE TITLE
Directory referenced in "Using a Private Registry" documentation does not exist

### ISSUE THREAD

**Issue by ScubaDrew** [kubernetes/kubernetes.github.io#468]
I'm following the instructions to setup a private registry here:

https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/images.md

I've placed the docker.json file on each node and tested the following:

```
admin@ip-172-20-0-177:~$ sudo docker pull docker.testx.net/tg
Using default tag: latest
latest: Pulling from tg
5981c1149c75: Pull complete 
3e3b4c6f1ae9: Pull complete 
e19d070fabab: Pull complete 
Digest: sha256:32f8be8240661cfe4197083e980d2eb15808895c6bb90747f940497a10616b89
Status: Downloaded newer image for docker.testx.net/tg:latest
```

So it appears the docker system is able to connect and download images.

Here is my RC:

```
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: tg
  name: tg
spec:
  replicas: 1
  selector:
    name: tg
  template:
    metadata:
      labels:
        name: tg
    spec:
      containers:
        - image: docker.testx.net/tg
          name: tg-identity
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /config
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: vault-config-dev
```

The image fails to pull:

```
kubectl get pods
NAME                        READY     STATUS         RESTARTS   AGE
cassandra-dev-2bhkc         1/1       Running        0          19h
cassandra-dev-96nym         1/1       Running        0          19h
tg-identity-p0ifn   0/1       ErrImagePull   0          5s
```

```
kubectl describe pod tg-identity-p0ifn
Name:       tg-identity-p0ifn
Namespace:  default
Node:       ip-172-20-0-178.us-west-2.compute.internal/172.20.0.178
Start Time: Thu, 05 May 2016 11:13:04 -0700
Labels:     name=tg-identity
Status:     Pending
IP:     10.244.0.5
Controllers:    ReplicationController/tg-identity
Containers:
  tg-identity:
    Container ID:   
    Image:      docker.testx.net/tg
    Image ID:       
    Port:       80/TCP
    QoS Tier:
      memory:   BestEffort
      cpu:  Burstable
    Requests:
      cpu:      100m
    State:      Waiting
      Reason:       ImagePullBackOff
    Ready:      False
    Restart Count:  0
    Environment Variables:
Conditions:
  Type      Status
  Ready     False 
Volumes:
  config-volume:
    Type:   ConfigMap (a volume populated by a ConfigMap)
    Name:   vault-config-dev
  default-token-f5ui2:
    Type:   Secret (a volume populated by a Secret)
    SecretName: default-token-f5ui2
Events:
  FirstSeen LastSeen    Count   From                            SubobjectPath               Type        Reason      Message
  --------- --------    -----   ----                            -------------               --------    ------      -------
  2m        2m      1   {default-scheduler }                                        Normal      Scheduled   Successfully assigned tg-identity-p0ifn to ip-172-20-0-178.us-west-2.compute.internal
  2m        1m      4   {kubelet ip-172-20-0-178.us-west-2.compute.internal}    spec.containers{tg-service-identity}    Normal      Pulling     pulling image "docker.testx.net/tg"
  2m        1m      4   {kubelet ip-172-20-0-178.us-west-2.compute.internal}    spec.containers{tg-service-identity}    Warning     Failed      Failed to pull image "docker.testx.net/tg": image pull failed for docker.testx.net/tg, this may be because there are no credentials on this request.  details: (Error: image tg:latest not found)
  2m        1m      4   {kubelet ip-172-20-0-178.us-west-2.compute.internal}                        Warning     FailedSync  Error syncing pod, skipping: failed to "StartContainer" for "tg-service-identity" with ErrImagePull: "image pull failed for docker.testx.net/tg, this may be because there are no credentials on this request.  details: (Error: image tg:latest not found)"

  2m    3s  10  {kubelet ip-172-20-0-178.us-west-2.compute.internal}    spec.containers{tg-service-identity}    Normal  BackOff     Back-off pulling image "docker.testx.net/tg"
  2m    3s  10  {kubelet ip-172-20-0-178.us-west-2.compute.internal}                        Warning FailedSync  Error syncing pod, skipping: failed to "StartContainer" for "tg-service-identity" with ImagePullBackOff: "Back-off pulling image \"docker.testx.net/tg\""
```
