### ISSUE TITLE
PetSet Documentation

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes.github.io#510]
I know it will be worked on before the 1.3 release.  Just let me know when ...

I kinda need it ...

cc: @bgrant0607

**Comment by bgrant0607** [comment]
cc @bprashanth @smarterclayton

**Comment by bprashanth** [comment]
@chrislovecnm what do you need, the c* example from contrib is insufficient?

**Comment by chrislovecnm** [comment]
Short term I would really like the definitions for 

```yaml
volumeClaimTemplates:
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  - metadata:
      name: cass_datadir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
```

I have a demo for the product launch... so just trying to get the example correct, so that I can build the demo off of it.
