### ISSUE TITLE
I wish /docs/user-guide/networkpolicies/ used the correct schema for NetworkPolicy

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes.github.io#801]
When I try creating the example given in that page, I get this error:
```
$ kubectl create -f zork-np.yaml
error validating "zork-np.yaml": error validating data: expected type array, for field spec.ingress[0].from, got map; if you choose to ignore these errors, turn validation off with --validate=false
```
Indeed, after I change the value of `from` from a map to a list containing that map, the create succeeds.  Here is the corrected source:
```yaml
kind: NetworkPolicy
metadata:
 name: test-network-policy
spec:
 podSelector:
  matchLabels:
    role: db
 ingress:
  - from:
    - podSelector:
        matchLabels:
          role: frontend
    ports:
     - protocol: tcp
       port: 6379
```
